USE [CMS]
GO

/****** Object:  StoredProcedure [dbo].[USP_CMS_RECOMMEND_EACH_POPULAR_VIDEO]    Script Date: 2021-04-13 오후 4:28:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-------------------------------------------------------------------------------------------
-- 프로시저명 : USP_CMS_RECOMMEND_EACH_POPULAR_VIDEO
-- 내      용 : 유저의 타입별 인기있는 비디오 추천
-- 작  성  일 : 2021-03-08
-- 작  성  자 : 김 명 희  
-- EXEC USP_CMS_RECOMMEND_EACH_POPULAR_VIDEO  '15', '1'
-- 이       력 : 
-------------------------------------------------------------------------------------------
CREATE PROC [dbo].[USP_CMS_RECOMMEND_EACH_POPULAR_VIDEO]
	@VIDEO_TYPE CHAR(2),
	@START INT
AS  
SET NOCOUNT ON;  
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;  
 
BEGIN
	SELECT  CASE ISNULL(SPL.SUB_PLAY_LIST,'')  
				WHEN '' THEN   V.TITLE
				ELSE YPL.PLAY_LIST_TITLE
				END AS TITLE
			, WVT.CNT
			, WVT.CREATED_AT
			, V.VIDEO_LENGTH
			, V.[DESCRIPTION]
			, V.VIDEO_URL
			, ROW_NUMBER() OVER(ORDER BY CNT DESC) AS ROWNUM
			, WVT.VIDEO_TYPE_NAME
			, V.PICTURE_URL
			, V.TAGS
			, V.KIDS_YN
		FROM( 
		SELECT  W.VIDEO_ID
				, dbo.FN_GET_VIDEO_TYPE_NAME(200, V.VIDEO_TYPE) AS VIDEO_TYPE_NAME
				, COUNT (W.VIDEO_ID) AS 'CNT' 
				, W.CREATED_AT
		FROM CUST.dbo.CUST_WATCHING W  
			INNER JOIN VIDEO V
			ON W.VIDEO_ID = V.VIDEO_ID
		WHERE V.VIDEO_TYPE = @VIDEO_TYPE
		GROUP BY W.VIDEO_ID, V.VIDEO_TYPE, W.CREATED_AT
		) WVT
		INNER JOIN VIDEO V
		ON V.VIDEO_ID = WVT.VIDEO_ID
		LEFT JOIN SUB_PLAY_LIST SPL
		ON WVT.VIDEO_ID = SPL.VIDEO_ID
		LEFT JOIN YOUTUBER_PLAY_LIST YPL
		ON SPL.SUB_PLAY_LIST = YPL.PLAY_LIST_ID
		ORDER BY WVT.CREATED_AT
		OFFSET(@START-1)*7 ROW
		FETCH NEXT 7 ROW ONLY
END
GO

